import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { join } from "node:path";
import { parse as parseEnv } from "dotenv";
import { paths, getMode } from "./config.js";
import { info } from "./output.js";

export const DOCKER_ENV_PATH = "docker/.env";

/** Minimal slice of the project config needed to build the seed environment. */
interface SeedConfig {
  postgres: { user: string; password: string; database: string };
  ports: { postgres: number };
}

/**
 * Build the environment for the host-side demo seed (`scripts/seed-demo.mjs`).
 *
 * In Docker mode three things must hold so seeded connectors work at runtime:
 *   - stored connection URIs use Docker service names (NEO4J_HOST / PG_HOST),
 *   - the host-side seed reaches the published Postgres port via localhost,
 *   - credentials are encrypted with the SAME ENCRYPTION_KEY the app container
 *     uses (from docker/.env) — otherwise they can't be decrypted (#969, #1039).
 *
 * In local mode `seed-demo.mjs` reads `app/.env.local` itself, so the unchanged
 * `process.env` is returned.
 *
 * Centralised here, and keyed on `getMode()` rather than a per-call flag, so no
 * seed entry point (`neoboard demo`, `demo seed`, `db seed`, `db reset`) can
 * silently forget the key.
 */
export function buildSeedEnv(config: SeedConfig): NodeJS.ProcessEnv {
  if (getMode() !== "docker") return process.env;

  const env: NodeJS.ProcessEnv = {
    ...process.env,
    NEO4J_HOST: "neoboard-neo4j",
    PG_HOST: "neoboard-postgres",
  };

  // Encode DSN components — a password like "pa:ss@word" must not break the
  // URI (CodeRabbit, PR #1062).
  const { user, password, database } = config.postgres;
  env.DATABASE_URL =
    env.DATABASE_URL ??
    `postgresql://${encodeURIComponent(user)}:${encodeURIComponent(password)}@localhost:${config.ports.postgres}/${encodeURIComponent(database)}`;

  if (!env.ENCRYPTION_KEY) {
    const secrets = readDockerEnvSecrets();
    if (secrets.ENCRYPTION_KEY) env.ENCRYPTION_KEY = secrets.ENCRYPTION_KEY;
  }

  return env;
}

/**
 * Per-install secrets for the full-stack compose (#970). The compose file
 * used to ship literal ENCRYPTION_KEY/NEXTAUTH_SECRET values in a public
 * repo — every demo install worldwide encrypted stored connector
 * credentials with the same publicly-known AES key.
 *
 * Generates docker/.env (gitignored) on first full-stack start and NEVER
 * overwrites it: a regenerated ENCRYPTION_KEY would make previously stored
 * credentials unrecoverable. Compose receives it via --env-file; process
 * env still wins, so CI can keep its workflow-level fixed values.
 */
export function ensureDockerEnvFile(): string {
  const envPath = join(paths.root, DOCKER_ENV_PATH);
  if (existsSync(envPath)) {
    return envPath;
  }

  const secret = () => randomBytes(32).toString("hex");
  const lines = [
    "# Generated by the neoboard CLI — per-install secrets for the",
    "# full-stack compose. Do not commit. Losing ENCRYPTION_KEY makes",
    "# stored connector credentials unrecoverable.",
    `ENCRYPTION_KEY=${secret()}`,
    `NEXTAUTH_SECRET=${secret()}`,
    `API_KEY_HMAC_SECRET=${secret()}`,
    // Required to create the very first admin: signup.ts rejects the
    // first-user branch unless ADMIN_BOOTSTRAP_TOKEN is set on the server.
    // Omitting it left Docker installs with an instance nobody could log
    // into — no value the user typed could ever match an unset var (#1312).
    `ADMIN_BOOTSTRAP_TOKEN=${secret()}`,
    "",
  ];
  writeFileSync(envPath, lines.join("\n"));
  info(`Generated per-install secrets in ${DOCKER_ENV_PATH}`);
  return envPath;
}

/**
 * Read the per-install secrets from docker/.env (#969). Used by the
 * host-side demo seed so it encrypts connector credentials with the SAME
 * ENCRYPTION_KEY the app container uses — otherwise seeded connectors
 * can't be decrypted at runtime. Returns {} if the file doesn't exist.
 */
export function readDockerEnvSecrets(): Record<string, string> {
  const envPath = join(paths.root, DOCKER_ENV_PATH);
  if (!existsSync(envPath)) return {};
  return parseEnv(readFileSync(envPath, "utf-8"));
}
