import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { join } from "node:path";
import { paths } from "./config.js";
import { info } from "./output.js";

export const DOCKER_ENV_PATH = "docker/.env";

/**
 * Per-install secrets for the full-stack compose (#970). The compose file
 * used to ship literal ENCRYPTION_KEY/NEXTAUTH_SECRET values in a public
 * repo — every demo install worldwide encrypted stored connector
 * credentials with the same publicly-known AES key.
 *
 * Generates docker/.env (gitignored) on first full-stack start and NEVER
 * overwrites it: a regenerated ENCRYPTION_KEY would make previously stored
 * credentials unrecoverable. Compose receives it via --env-file; process
 * env still wins, so CI can keep its workflow-level fixed values.
 */
export function ensureDockerEnvFile(): string {
  const envPath = join(paths.root, DOCKER_ENV_PATH);
  if (existsSync(envPath)) {
    return envPath;
  }

  const secret = () => randomBytes(32).toString("hex");
  const lines = [
    "# Generated by the neoboard CLI — per-install secrets for the",
    "# full-stack compose. Do not commit. Losing ENCRYPTION_KEY makes",
    "# stored connector credentials unrecoverable.",
    `ENCRYPTION_KEY=${secret()}`,
    `NEXTAUTH_SECRET=${secret()}`,
    `API_KEY_HMAC_SECRET=${secret()}`,
    "",
  ];
  writeFileSync(envPath, lines.join("\n"));
  info(`Generated per-install secrets in ${DOCKER_ENV_PATH}`);
  return envPath;
}

/**
 * Read the per-install secrets from docker/.env (#969). Used by the
 * host-side demo seed so it encrypts connector credentials with the SAME
 * ENCRYPTION_KEY the app container uses — otherwise seeded connectors
 * can't be decrypted at runtime. Returns {} if the file doesn't exist.
 */
export function readDockerEnvSecrets(): Record<string, string> {
  const envPath = join(paths.root, DOCKER_ENV_PATH);
  if (!existsSync(envPath)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(envPath, "utf-8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    out[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return out;
}
