import { existsSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { join } from "node:path";
import { paths } from "./config.js";
import { info } from "./output.js";

export const DOCKER_ENV_PATH = "docker/.env";

/**
 * Per-install secrets for the full-stack compose (#970). The compose file
 * used to ship literal ENCRYPTION_KEY/NEXTAUTH_SECRET values in a public
 * repo — every demo install worldwide encrypted stored connector
 * credentials with the same publicly-known AES key.
 *
 * Generates docker/.env (gitignored) on first full-stack start and NEVER
 * overwrites it: a regenerated ENCRYPTION_KEY would make previously stored
 * credentials unrecoverable. Compose receives it via --env-file; process
 * env still wins, so CI can keep its workflow-level fixed values.
 */
export function ensureDockerEnvFile(): string {
  const envPath = join(paths.root, DOCKER_ENV_PATH);
  if (existsSync(envPath)) {
    return envPath;
  }

  const secret = () => randomBytes(32).toString("hex");
  const lines = [
    "# Generated by the neoboard CLI — per-install secrets for the",
    "# full-stack compose. Do not commit. Losing ENCRYPTION_KEY makes",
    "# stored connector credentials unrecoverable.",
    `ENCRYPTION_KEY=${secret()}`,
    `NEXTAUTH_SECRET=${secret()}`,
    `API_KEY_HMAC_SECRET=${secret()}`,
    "",
  ];
  writeFileSync(envPath, lines.join("\n"));
  info(`Generated per-install secrets in ${DOCKER_ENV_PATH}`);
  return envPath;
}
