import type { StorybookConfig } from "@storybook/react-vite";

const config: StorybookConfig = {
  // No MDX glob: docs pages are generated by `autodocs` from JSDoc on the
  // components (#1130), so the init template's "../stories/**/*.mdx" matched
  // nothing and warned on every start (#1251). Re-add it only if hand-written
  // MDX docs are actually introduced.
  stories: ["../stories/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  addons: [
    "@chromatic-com/storybook",
    "@storybook/addon-vitest",
    "@storybook/addon-a11y",
    "@storybook/addon-docs",
    "@storybook/addon-onboarding",
  ],
  framework: "@storybook/react-vite",
};
export default config;
