/**
 * GraphExplorationWrapper — synthetic (APOC virtual) node handling (#1361).
 *
 * A virtual node has no rows behind it, so `MATCH (n) WHERE elementId(n) = $id`
 * returns nothing. Before this, the context menu offered "Expand" anyway and
 * the user got a silent empty result, indistinguishable from a node that
 * genuinely has no neighbours.
 *
 * `canExpand` is deliberately mocked to return true for every node, so these
 * tests fail unless the menu itself declines — they cannot pass by leaning on
 * the hook's own guard (which is covered in component/).
 */
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { render, screen, cleanup, fireEvent } from "@testing-library/react";
import React from "react";
import type { GraphNode } from "@neoboard/components";

const onExpandRequest = vi.fn();

vi.mock("@neoboard/components", () => ({
  GraphChart: ({
    nodes,
    onNodeRightClick,
  }: {
    nodes: GraphNode[];
    onNodeRightClick?: (e: {
      node: GraphNode;
      position: { x: number; y: number };
    }) => void;
  }) => (
    <div data-testid="graph-chart">
      {nodes.map((n) => (
        <button
          key={n.id}
          data-testid={`right-click-${n.id}`}
          onClick={() =>
            onNodeRightClick?.({ node: n, position: { x: 10, y: 10 } })
          }
        >
          {n.label}
        </button>
      ))}
    </div>
  ),
  PropertyPanel: () => <div data-testid="property-panel" />,
  Badge: ({ children }: { children: React.ReactNode }) => (
    <span>{children}</span>
  ),
  useGraphExploration: ({
    initialNodes,
    initialEdges,
  }: {
    initialNodes: GraphNode[];
    initialEdges: unknown[];
  }) => ({
    nodes: initialNodes,
    edges: initialEdges,
    selectedNodeIds: [],
    expandingNodeId: null,
    expandedNodeIds: [],
    onNodeSelect: vi.fn(),
    onExpandRequest,
    collapse: vi.fn(),
    reset: vi.fn(),
    // Permissive on purpose — the menu must decline on its own.
    canExpand: () => true,
    canCollapse: () => false,
  }),
}));

vi.mock("@/lib/plugin/chart-helpers", () => ({
  getChartConfig: () => ({ transform: (d: unknown) => d }),
}));

vi.mock("@/stores/graph-widget-store", () => ({
  useGraphWidgetStore: (selector: (s: unknown) => unknown) =>
    selector({ setState: vi.fn(), states: {} }),
}));

vi.mock("@/lib/api/api-client", () => ({
  unwrapFullResponse: vi.fn(),
}));

import { GraphExplorationWrapper } from "../graph-exploration-wrapper";

const realNode: GraphNode = {
  id: "4:1a7aa765-ebcb-4a7b-9859-ca21d0d78e50:0",
  label: "Document",
  labels: ["Document"],
};

const virtualNode: GraphNode = {
  id: "-289",
  label: "Totals",
  labels: ["Summary"],
  synthetic: true,
};

function renderWrapper() {
  return render(
    <GraphExplorationWrapper
      widgetId="w1"
      nodes={[realNode, virtualNode]}
      edges={[]}
      connectionId="c1"
      settings={{}}
    />,
  );
}

describe("GraphExplorationWrapper — synthetic nodes", () => {
  beforeEach(() => {
    onExpandRequest.mockClear();
  });
  afterEach(() => cleanup());

  it("offers Expand on a real node", () => {
    renderWrapper();
    fireEvent.click(screen.getByTestId(`right-click-${realNode.id}`));
    expect(screen.getByRole("button", { name: "Expand" })).toBeInTheDocument();
  });

  it("does not offer Expand on a synthetic node", () => {
    renderWrapper();
    fireEvent.click(screen.getByTestId("right-click--289"));
    expect(
      screen.queryByRole("button", { name: "Expand" }),
    ).not.toBeInTheDocument();
  });

  it("explains why a synthetic node cannot be expanded", () => {
    renderWrapper();
    fireEvent.click(screen.getByTestId("right-click--289"));
    const note = screen.getByTestId("graph-synthetic-note");
    expect(note).toBeInTheDocument();
    // The explanation must name the cause and the consequence.
    expect(note.textContent).toMatch(/virtual/i);
    expect(note.textContent).toMatch(/generated by the query/i);
    expect(note.textContent).toMatch(/no neighbours in the database/i);
  });

  it("shows no explanation on a real node", () => {
    renderWrapper();
    fireEvent.click(screen.getByTestId(`right-click-${realNode.id}`));
    expect(
      screen.queryByTestId("graph-synthetic-note"),
    ).not.toBeInTheDocument();
  });

  it("styles the explanation as secondary text, not an error", () => {
    renderWrapper();
    fireEvent.click(screen.getByTestId("right-click--289"));
    const note = screen.getByTestId("graph-synthetic-note");
    expect(note.className).toContain("text-muted-foreground");
    expect(note.className).not.toContain("destructive");
  });

  it("still offers Properties on a synthetic node", () => {
    renderWrapper();
    fireEvent.click(screen.getByTestId("right-click--289"));
    expect(
      screen.getByRole("button", { name: "Properties" }),
    ).toBeInTheDocument();
  });
});
